---
title: "Stan model_1: Hierarchical models"
---

Generating fake data to determine the number of polls needed (`K`) for an accurate estimation of the parameter of interest in the polling example in `model_1.4`.

```{r}
K = 5
aN = 10
theta = .35
Y = rbinom(K, aN, theta)
N = rep(aN, K)
```

Fit previously defined model

```{r}
aModel = stan_model('stanModels/model_1.4.stan')
fit = sampling(aModel, data = list(N=N, K=K, Y=Y), iter=400, chains=4)
```

Look at the estimates to see if they are close to the ground truth defined above.

```{r}
print(fit, probs=c(.25,.5,.75))
```

````{r}
data.frame(aTheta =extract(fit, 'aTheta')[[1]]) %>%
  ggplot(aes(x=aTheta))+
  geom_histogram()+
  geom_vline(aes(xintercept=.35), linetype='dashed')
```

Repeat same thing with data from more polls

```{r}
K = 30
aN = 10
theta = .35
Y = rbinom(K, aN, theta)
N = rep(aN, K)
```

Fit previously defined model

```{r}
fit2 = sampling(aModel, data = list(N=N, K=K, Y=Y), iter=400, chains=4)
```

```{r}
print(fit2, probs=c(.25,.5,.75))
```

````{r}
data.frame(aTheta =extract(fit2, 'aTheta')[[1]]) %>%
  ggplot(aes(x=aTheta))+
  geom_histogram()+
  geom_vline(aes(xintercept=.35), linetype='dashed')
```