---
title: "RL simulation and parameter recovery with Stan III: Model comparison"
---

**Even if we can't do a good job with estimating the exact parameters for subjects can we distinguish between (cognitive) models and reliably identify the correct data generating process?**

```{r}
source('/Users/zeynepenkavi/Dropbox/RangelLab/BayesianStats/helpers/demo_QlearningSimulation.R')
library(loo)
library(caret)
```

```{r}
sim_data = demo_QlearningSimulation(alpha = .65, beta = 2.5)
```

True learning rate `alpha`

```{r}
true_alpha = VBA_sigmoid(sim_data$simulation$evolution, inverse=FALSE)
true_alpha
```

True inverse temperature `beta`

```{r}
true_beta = exp(sim_data$simulation$observation)
true_beta
```

Use `caret` to make folds for cross validation.

```{r}
testIndices = createFolds(sim_data$choices, k = 5, list=TRUE, returnTrain = FALSE)
```

Use `stan` to get parameters that generated simulated data.

```{r}
## Adapted from Lambert textbook p. 397
k_fold = function(aModel, testIndices, simData){
  numFolds = length(testIndices)
  
  #expected log pointwise predictive density
  lPointLogLikelihoodTotal = vector()
  
  for(i in 1:numFolds){
    cur_ind = testIndices[[i]]
  
    T_train = length(sim_data$choices) - length(cur_ind)
    T_test = length(cur_ind)
  
    choice_train = sim_data$choices[-cur_ind] #adding 1 bc categorical_logit has support over [1,2]
    choice_test = sim_data$choices[cur_ind]
    
    outcome_train = sim_data$feedback[-cur_ind] 
    outcome_test = sim_data$feedback[cur_ind] 
    
    m_data = list(T_train = T_train, T_test = T_test, 
                  choice_train = choice_train, choice_test = choice_test, 
                  outcome_train = outcome_train, outcome_test = outcome_test)
    
    fit = sampling(aModel, iter=1000, chains=4, data=m_data)
    
    logLikelihood1 = extract_log_lik(fit, 'log_lik')
    lPointLogLikelihood1 = colMeans(logLikelihood1)
    lPointLogLikelihoodTotal = c(lPointLogLikelihoodTotal, lPointLogLikelihood1)
  }
  return(lPointLogLikelihoodTotal)
}
```

```{r}
m_true = stan_model('../stanModels/QLearning_trueModel.stan')
```

```{r}
m_false = stan_model('../stanModels/QLearning_falseModel.stan')
```

```{r}
lELPD1 = k_fold(m_true, testIndices, sim_data)
```

```{r}
lELPD2 = k_fold(m_false, testIndices, sim_data)
```

```{r}
sum(lELPD1)
```

```{r}
sum(lELPD2)
```

