---
title: "R Notebook"
---

Based on this [vignette](https://mc-stan.org/users/documentation/case-studies/lotka-volterra-predator-prey.html#mechanistic-model-the-lotka-volterra-equations).

```{r}
lynx_hare_df = read.csv("stanModels/hudson-bay-lynx-hare.csv", comment.char="#")
```

```{r}
N = length(lynx_hare_df$Year) - 1
ts = 1:N
y_init = c(lynx_hare_df$Hare[1], lynx_hare_df$Lynx[1])
y = as.matrix(lynx_hare_df[2:(N + 1), 2:3])
y = cbind(y[ , 2], y[ , 1]); # hare, lynx order
lynx_hare_data = list(N = N, ts = ts, y_init = y_init, y = y)
```

```{r}
mod = cmdstan_model("stanModels/lotka-volterra.stan")
```

```{r}
fit <- mod$sample(
  data = lynx_hare_data,
  seed = 123
)
```

What does predicted versus true look like? How does the ODE solver work?

```{r}
fit$summary("z") %>%
  select(variable, mean) %>%
  separate(variable, sep = ",", into=c("time", "key")) %>%
  mutate(time = gsub("z\\[", "", time),
         key = gsub("\\]", "", key),
         time = as.numeric(time),
         key = ifelse(key == 1, "Hare", "Lynx"),
         type = "est") %>%
  rename(value=mean) %>%
  rbind(lynx_hare_df %>%
          slice(-1) %>% ## Don't forget it's modeling change so drop first time point!!
        select(-Year)%>%
        mutate(time = 1:n(),
               type = "true") %>%
  gather(key, value, -time, -type)) %>%
  spread(type, value) %>%
  ggplot(aes(est, true))+
  geom_point()+
  geom_abline(aes(intercept=0, slope=1))+
  facet_wrap(~key)


```